// Code generated by counterfeiter. DO NOT EDIT.
package uidgidfakes

import (
	"os"
	"os/exec"
	"sync"

	"github.com/concourse/baggageclaim/uidgid"
)

type FakeTranslator struct {
	TranslatePathStub        func(path string, info os.FileInfo, err error) error
	translatePathMutex       sync.RWMutex
	translatePathArgsForCall []struct {
		path string
		info os.FileInfo
		err  error
	}
	translatePathReturns struct {
		result1 error
	}
	translatePathReturnsOnCall map[int]struct {
		result1 error
	}
	TranslateCommandStub        func(*exec.Cmd)
	translateCommandMutex       sync.RWMutex
	translateCommandArgsForCall []struct {
		arg1 *exec.Cmd
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTranslator) TranslatePath(path string, info os.FileInfo, err error) error {
	fake.translatePathMutex.Lock()
	ret, specificReturn := fake.translatePathReturnsOnCall[len(fake.translatePathArgsForCall)]
	fake.translatePathArgsForCall = append(fake.translatePathArgsForCall, struct {
		path string
		info os.FileInfo
		err  error
	}{path, info, err})
	fake.recordInvocation("TranslatePath", []interface{}{path, info, err})
	fake.translatePathMutex.Unlock()
	if fake.TranslatePathStub != nil {
		return fake.TranslatePathStub(path, info, err)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.translatePathReturns.result1
}

func (fake *FakeTranslator) TranslatePathCallCount() int {
	fake.translatePathMutex.RLock()
	defer fake.translatePathMutex.RUnlock()
	return len(fake.translatePathArgsForCall)
}

func (fake *FakeTranslator) TranslatePathArgsForCall(i int) (string, os.FileInfo, error) {
	fake.translatePathMutex.RLock()
	defer fake.translatePathMutex.RUnlock()
	return fake.translatePathArgsForCall[i].path, fake.translatePathArgsForCall[i].info, fake.translatePathArgsForCall[i].err
}

func (fake *FakeTranslator) TranslatePathReturns(result1 error) {
	fake.TranslatePathStub = nil
	fake.translatePathReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTranslator) TranslatePathReturnsOnCall(i int, result1 error) {
	fake.TranslatePathStub = nil
	if fake.translatePathReturnsOnCall == nil {
		fake.translatePathReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.translatePathReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTranslator) TranslateCommand(arg1 *exec.Cmd) {
	fake.translateCommandMutex.Lock()
	fake.translateCommandArgsForCall = append(fake.translateCommandArgsForCall, struct {
		arg1 *exec.Cmd
	}{arg1})
	fake.recordInvocation("TranslateCommand", []interface{}{arg1})
	fake.translateCommandMutex.Unlock()
	if fake.TranslateCommandStub != nil {
		fake.TranslateCommandStub(arg1)
	}
}

func (fake *FakeTranslator) TranslateCommandCallCount() int {
	fake.translateCommandMutex.RLock()
	defer fake.translateCommandMutex.RUnlock()
	return len(fake.translateCommandArgsForCall)
}

func (fake *FakeTranslator) TranslateCommandArgsForCall(i int) *exec.Cmd {
	fake.translateCommandMutex.RLock()
	defer fake.translateCommandMutex.RUnlock()
	return fake.translateCommandArgsForCall[i].arg1
}

func (fake *FakeTranslator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.translatePathMutex.RLock()
	defer fake.translatePathMutex.RUnlock()
	fake.translateCommandMutex.RLock()
	defer fake.translateCommandMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTranslator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ uidgid.Translator = new(FakeTranslator)
