// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/concourse/baggageclaim/volume"
)

type FakeDriver struct {
	CreateVolumeStub        func(path string) error
	createVolumeMutex       sync.RWMutex
	createVolumeArgsForCall []struct {
		path string
	}
	createVolumeReturns struct {
		result1 error
	}
	DestroyVolumeStub        func(path string) error
	destroyVolumeMutex       sync.RWMutex
	destroyVolumeArgsForCall []struct {
		path string
	}
	destroyVolumeReturns struct {
		result1 error
	}
	GetVolumeSizeStub        func(path string) (uint, error)
	getVolumeSizeMutex       sync.RWMutex
	getVolumeSizeArgsForCall []struct {
		path string
	}
	getVolumeSizeReturns struct {
		result1 uint
		result2 error
	}
	CreateCopyOnWriteLayerStub        func(path string, parent string) error
	createCopyOnWriteLayerMutex       sync.RWMutex
	createCopyOnWriteLayerArgsForCall []struct {
		path   string
		parent string
	}
	createCopyOnWriteLayerReturns struct {
		result1 error
	}
}

func (fake *FakeDriver) CreateVolume(path string) error {
	fake.createVolumeMutex.Lock()
	fake.createVolumeArgsForCall = append(fake.createVolumeArgsForCall, struct {
		path string
	}{path})
	fake.createVolumeMutex.Unlock()
	if fake.CreateVolumeStub != nil {
		return fake.CreateVolumeStub(path)
	} else {
		return fake.createVolumeReturns.result1
	}
}

func (fake *FakeDriver) CreateVolumeCallCount() int {
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	return len(fake.createVolumeArgsForCall)
}

func (fake *FakeDriver) CreateVolumeArgsForCall(i int) string {
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	return fake.createVolumeArgsForCall[i].path
}

func (fake *FakeDriver) CreateVolumeReturns(result1 error) {
	fake.CreateVolumeStub = nil
	fake.createVolumeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDriver) DestroyVolume(path string) error {
	fake.destroyVolumeMutex.Lock()
	fake.destroyVolumeArgsForCall = append(fake.destroyVolumeArgsForCall, struct {
		path string
	}{path})
	fake.destroyVolumeMutex.Unlock()
	if fake.DestroyVolumeStub != nil {
		return fake.DestroyVolumeStub(path)
	} else {
		return fake.destroyVolumeReturns.result1
	}
}

func (fake *FakeDriver) DestroyVolumeCallCount() int {
	fake.destroyVolumeMutex.RLock()
	defer fake.destroyVolumeMutex.RUnlock()
	return len(fake.destroyVolumeArgsForCall)
}

func (fake *FakeDriver) DestroyVolumeArgsForCall(i int) string {
	fake.destroyVolumeMutex.RLock()
	defer fake.destroyVolumeMutex.RUnlock()
	return fake.destroyVolumeArgsForCall[i].path
}

func (fake *FakeDriver) DestroyVolumeReturns(result1 error) {
	fake.DestroyVolumeStub = nil
	fake.destroyVolumeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDriver) GetVolumeSize(path string) (uint, error) {
	fake.getVolumeSizeMutex.Lock()
	fake.getVolumeSizeArgsForCall = append(fake.getVolumeSizeArgsForCall, struct {
		path string
	}{path})
	fake.getVolumeSizeMutex.Unlock()
	if fake.GetVolumeSizeStub != nil {
		return fake.GetVolumeSizeStub(path)
	} else {
		return fake.getVolumeSizeReturns.result1, fake.getVolumeSizeReturns.result2
	}
}

func (fake *FakeDriver) GetVolumeSizeCallCount() int {
	fake.getVolumeSizeMutex.RLock()
	defer fake.getVolumeSizeMutex.RUnlock()
	return len(fake.getVolumeSizeArgsForCall)
}

func (fake *FakeDriver) GetVolumeSizeArgsForCall(i int) string {
	fake.getVolumeSizeMutex.RLock()
	defer fake.getVolumeSizeMutex.RUnlock()
	return fake.getVolumeSizeArgsForCall[i].path
}

func (fake *FakeDriver) GetVolumeSizeReturns(result1 uint, result2 error) {
	fake.GetVolumeSizeStub = nil
	fake.getVolumeSizeReturns = struct {
		result1 uint
		result2 error
	}{result1, result2}
}

func (fake *FakeDriver) CreateCopyOnWriteLayer(path string, parent string) error {
	fake.createCopyOnWriteLayerMutex.Lock()
	fake.createCopyOnWriteLayerArgsForCall = append(fake.createCopyOnWriteLayerArgsForCall, struct {
		path   string
		parent string
	}{path, parent})
	fake.createCopyOnWriteLayerMutex.Unlock()
	if fake.CreateCopyOnWriteLayerStub != nil {
		return fake.CreateCopyOnWriteLayerStub(path, parent)
	} else {
		return fake.createCopyOnWriteLayerReturns.result1
	}
}

func (fake *FakeDriver) CreateCopyOnWriteLayerCallCount() int {
	fake.createCopyOnWriteLayerMutex.RLock()
	defer fake.createCopyOnWriteLayerMutex.RUnlock()
	return len(fake.createCopyOnWriteLayerArgsForCall)
}

func (fake *FakeDriver) CreateCopyOnWriteLayerArgsForCall(i int) (string, string) {
	fake.createCopyOnWriteLayerMutex.RLock()
	defer fake.createCopyOnWriteLayerMutex.RUnlock()
	return fake.createCopyOnWriteLayerArgsForCall[i].path, fake.createCopyOnWriteLayerArgsForCall[i].parent
}

func (fake *FakeDriver) CreateCopyOnWriteLayerReturns(result1 error) {
	fake.CreateCopyOnWriteLayerStub = nil
	fake.createCopyOnWriteLayerReturns = struct {
		result1 error
	}{result1}
}

var _ volume.Driver = new(FakeDriver)
