// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/concourse/baggageclaim/volume"
)

type FakeStrategy struct {
	MaterializeStub        func(string, volume.Filesystem) (volume.FilesystemInitVolume, error)
	materializeMutex       sync.RWMutex
	materializeArgsForCall []struct {
		arg1 string
		arg2 volume.Filesystem
	}
	materializeReturns struct {
		result1 volume.FilesystemInitVolume
		result2 error
	}
}

func (fake *FakeStrategy) Materialize(arg1 string, arg2 volume.Filesystem) (volume.FilesystemInitVolume, error) {
	fake.materializeMutex.Lock()
	fake.materializeArgsForCall = append(fake.materializeArgsForCall, struct {
		arg1 string
		arg2 volume.Filesystem
	}{arg1, arg2})
	fake.materializeMutex.Unlock()
	if fake.MaterializeStub != nil {
		return fake.MaterializeStub(arg1, arg2)
	} else {
		return fake.materializeReturns.result1, fake.materializeReturns.result2
	}
}

func (fake *FakeStrategy) MaterializeCallCount() int {
	fake.materializeMutex.RLock()
	defer fake.materializeMutex.RUnlock()
	return len(fake.materializeArgsForCall)
}

func (fake *FakeStrategy) MaterializeArgsForCall(i int) (string, volume.Filesystem) {
	fake.materializeMutex.RLock()
	defer fake.materializeMutex.RUnlock()
	return fake.materializeArgsForCall[i].arg1, fake.materializeArgsForCall[i].arg2
}

func (fake *FakeStrategy) MaterializeReturns(result1 volume.FilesystemInitVolume, result2 error) {
	fake.MaterializeStub = nil
	fake.materializeReturns = struct {
		result1 volume.FilesystemInitVolume
		result2 error
	}{result1, result2}
}

var _ volume.Strategy = new(FakeStrategy)
